name: bosch_to_s3
mode: batch
generator:
  type: bosch
  batch_size: 10000
handler:
  format: json
  compression: lz4
adapter:
  type: s3
  host: localhost
  port: 9000
  extra:
    endpoint: http://localhost:9000
    bucket: testdata
    access_key: testdata
    secret_key: testdata_dev_password
