name: ieee_fraud_to_kafka
mode: stream
generator:
  type: ieee_fraud
  batch_size: 1000
  stream_interval_ms: 10
handler:
  format: json
  compression: none
adapter:
  type: kafka
  host: localhost
  port: 9092
  extra:
    topic: ieee-fraud-events
