name: northwind_to_postgresql
mode: batch
generator:
  type: northwind
  batch_size: 5000
handler:
  format: json
  compression: none
adapter:
  type: postgresql
  host: localhost
  port: 5434
  extra:
    user: testdata
    password: testdata_dev
    database: testdata
