name: smart_mfg_to_mqtt
mode: stream
generator:
  type: smart_mfg
  batch_size: 500
  stream_interval_ms: 50
handler:
  format: json
  compression: none
adapter:
  type: mqtt
  host: localhost
  port: 1883
  extra:
    topic: iot/smart_mfg/sensors
