name: stackoverflow_to_elasticsearch
mode: batch
generator:
  type: stackoverflow
  batch_size: 5000
handler:
  format: json
  compression: none
adapter:
  type: elasticsearch
  host: localhost
  port: 9200
  extra:
    index: stackoverflow-posts
